/** Deterministic API fixtures for page tests: every list endpoint returns one representative row. */
const today = new Date().toISOString();
const date = today.slice(0, 10);
const client = { id: 1, client_no: 'CLT-2026-00001', name: 'Acme Logistics', type: 'corporate', email: 'acme@example.com', phone: '0917', tin: '123', pep: false, risk_score: 5, risk_tier: 'low', cdd_level: 'simplified', screening_status: 'clear', screened_at: today };
const policy = { id: 1, policy_no: 'POL-2026-00001', client_id: 1, client_name: 'Acme Logistics', client_no: 'CLT-2026-00001', product_code: 'MTR-CMP', product_name: 'Motor Comprehensive', insurer_name: 'Malayan Insurance', sftp_enrolled: true, sum_insured: 1000000, premium: 12500, vat: 1500, dst: 1562.5, lgt: 93.75, fst: 0, total_amount: 15656.25, commission: 1875, inception_date: date, expiry_date: date, status: 'in_force', epolicy_channel: 'sftp', epolicy_sent_at: today, placement_requested_at: today, placed_at: today, booked_at: today, issued_at: today, insurer_policy_ref: 'MAL-1' };
const invoice = { id: 1, invoice_no: 'INV-2026-00001', policy_no: 'POL-2026-00001', client_id: 1, client_name: 'Acme Logistics', amount: 15656.25, paid_amount: 0, balance: 15656.25, due_date: date, status: 'open', days_overdue: 0, days_since_booking: 1, bucket: 'current', stage: 'newly_booked', last_category: 'committed', commitment_date: date };
const claim = { id: 1, claim_no: 'CLM-2026-00001', policy_no: 'POL-2026-00001', client_name: 'Acme Logistics', client_id: 1, product_name: 'Motor Comprehensive', insurer_name: 'Malayan Insurance', loss_date: date, reported_date: date, description: 'Collision', estimated_amount: 50000, reserve_amount: 50000, paid_amount: 0, offer_amount: 45000, offer_received_at: today, fla_sent_at: today, status: 'offer_received', age_days: 3, missing_documents: 0, adjuster_required: true, settlement_mode: 'loa', insurer_claim_ref: 'X', sum_insured: 1000000 };
const kpis = { policies_in_force: 3, in_placement: 1, premium_ytd: 100, commission_ytd: 10, outstanding_premium: 5, unapplied_payments: 1, pending_approvals: 2, disbursements_in_flight: 1, open_claims: 1, renewals_due: 1, past_tat_requests: 1, screening_hits: 1 };

export const FIXTURES: Record<string, unknown> = {
  '/api/reports/dashboard': { kpis, byProduct: [{ code: 'MTR-CMP', name: 'Motor', policies: 1, premium: 12500 }], byMonth: [{ month: '2026-09', policies: 1, premium: 12500 }], claimsByStatus: [{ status: 'registered', count: 1, reserve: 50000 }] },
  '/api/reports/production': { rows: [{ policy_no: 'POL-2026-00001', issued: date, client: 'Acme', product: 'MTR-CMP', insurer: 'Malayan', sum_insured: 1000000, premium: 12500, total_amount: 15656.25, commission: 1875, status: 'in_force' }] },
  '/api/clients': { clients: [client, { ...client, id: 2, name: 'Blocked Co', screening_status: 'hit' }] },
  '/api/clients/1': { client, hits: [{ id: 1, matched_name: 'Acme', list_source: 'OFAC', method: 'fuzzy', score: 80, decision: null }], policies: [policy] },
  '/api/products': { products: [{ id: 1, code: 'MTR-CMP', name: 'Motor Comprehensive', line: 'motor', packaged: true, base_rate: 0.0125, min_premium: 3000, commission_rate: 0.15, vat_rate: 0.12, dst_rate: 0.125, lgt_rate: 0.0075, fst_rate: 0.02, max_sum_insured: 5000000, status: 'active' }] },
  '/api/products/release-advisories': { advisories: [{ id: 1, advisory_no: 'RADV-1', product_code: 'MTR-CMP', summary: 'Rate change', changes: { baseRate: 0.013 }, effective_date: date, approved_by_name: 'Ramon', created_at: today }] },
  '/api/products/1/rate': { premium: 12500, vat: 1500, dst: 1562.5, lgt: 93.75, fst: 0, total: 15656.25, commission: 1875, surveyRequired: true, packaged: true },
  '/api/insurers': { insurers: [{ id: 1, code: 'MAL', name: 'Malayan Insurance', security_rating: 'A', accredited: true, sftp_enrolled: true, status: 'active' }, { id: 2, code: 'NAC', name: 'Non-Accredited', security_rating: 'A', accredited: false, sftp_enrolled: false, status: 'active' }] },
  '/api/tsu': { requests: [{ id: 1, request_no: 'TSU-1', client_id: 1, client_name: 'Acme', line: 'fire', sum_insured: 30000000, requires_ri: true, insurers_approached: 2, insurers_accepted: 1, selected_insurer_name: 'Malayan', status: 'sent_to_insurers', updated_at: today, quotation_slip: 'QS text', proposal_slip: null }] },
  '/api/tsu/1': { request: { id: 1, request_no: 'TSU-1', status: 'sent_to_insurers', quotation_slip: 'QS', proposal_slip: 'PS' }, responses: [{ id: 1, insurer_id: 1, insurer_name: 'Malayan', security_rating: 'A', response: 'accepted', premium: 70000, conditions: null, evidence: 'signed' }] },
  '/api/new-business/quotations': { quotations: [{ id: 1, quote_no: 'QT-1', client_name: 'Acme', product_code: 'MTR-CMP', insurer_name: 'Malayan', sum_insured: 1000000, total_amount: 15656.25, hold_cover_until: date, status: 'quoted' }, { id: 2, quote_no: 'QT-2', client_name: 'Acme', product_code: 'MTR-CMP', insurer_name: 'Malayan', sum_insured: 1, total_amount: 1, status: 'proposal_sent' }, { id: 3, quote_no: 'QT-3', client_name: 'Acme', product_code: 'MTR-CMP', insurer_name: 'Malayan', sum_insured: 1, total_amount: 1, status: 'accepted' }] },
  '/api/new-business/policies': { policies: [policy, { ...policy, id: 2, policy_no: 'POL-2026-00002', status: 'placement_requested' }, { ...policy, id: 3, policy_no: 'POL-2026-00003', status: 'returned', return_reason: 'Missing OR/CR' }, { ...policy, id: 4, policy_no: 'POL-2026-00004', status: 'placed' }, { ...policy, id: 5, policy_no: 'POL-2026-00005', status: 'pending_approval' }] },
  '/api/new-business/policies/1': { policy, invoices: [invoice], claims: [claim], cessions: [{ id: 1, treaty_code: 'QS', ceded_sum_insured: 1, ceded_premium: 1 }], journals: [{ jv_no: 'JV-1' }], endorsements: [{ id: 1, endorsement_no: 'END-1', type: 'adjustment', premium_delta: 100, refund_amount: 0, status: 'posted' }] },
  '/api/approvals': { approvals: [{ id: 1, request_type: 'policy_issue', summary: 'Book POL-2026-00001', maker_name: 'Maria', maker_id: 99, maker_note: 'please', created_at: today, status: 'pending', checker_name: null }, { id: 2, request_type: 'policy_issue', summary: 'Own', maker_name: 'Admin', maker_id: 1, created_at: today, status: 'pending' }] },
  '/api/audit': { entries: [{ id: 1, at: today, username: 'admin', action: 'policy.book', entity: 'policy', entity_id: '1', after: { x: 1 } }] },
  '/api/outbox': { emails: [{ id: 1, created_at: today, template: 'e-policy', to_addr: 'a@b', subject: 'Your e-Policy' }] },
  '/api/operations/invoices': { invoices: [invoice] },
  '/api/operations/receipts': { receipts: [] },
  '/api/operations/payments': { payments: [{ id: 1, payment_no: 'PAY-1', channel: 'otc_cheque', client_name: 'Acme', invoice_no: 'INV-1', amount: 1000, applied_amount: 0, unapplied_amount: 0, cheque_no: '000111', hold_until: date, receipt_no: null, status: 'held', exclusion_reason: null }, { id: 2, payment_no: 'PAY-2', channel: 'bills_payment', amount: 500, applied_amount: 0, unapplied_amount: 500, status: 'unapplied' }] },
  '/api/operations/direct-payments': { items: [{ id: 1, dp_no: 'DP-1', policy_no: 'POL-1', client_name: 'Acme', insurer_name: 'Malayan', amount: 1875, status: 'billed', receipt_no: null, billed_at: today }] },
  '/api/operations/endorsements': { endorsements: [{ id: 1, endorsement_no: 'END-1', policy_no: 'POL-1', client_name: 'Acme', type: 'adjustment', description: 'Add cover', premium_delta: 500, refund_amount: 0, status: 'pending_approval', posted_at: null }] },
  '/api/operations/production-recons': { recons: [{ id: 1, recon_no: 'PRC-1', insurer_name: 'Malayan', period: '2026-09', total_rows: 3, matched: 1, discrepancy: 1, unbooked: 1, created_at: today }] },
  '/api/operations/production-recons/1': { recon: { id: 1, recon_no: 'PRC-1', insurer_name: 'Malayan' }, rows: [{ id: 1, policy_no_raw: 'POL-1', premium_raw: 100, status: 'discrepancy', variance: -10, disposition: null }] },
  '/api/collections/outstanding': { invoices: [invoice], buckets: { current: 15656.25, '0-30': 0, '31-60': 0, '61-90': 0, '91-180': 0, '180+': 0 }, total: 15656.25 },
  '/api/collections/cte': { extensions: [{ id: 1, invoice_no: 'INV-1', client_name: 'Acme', requested_days: 30, reason: 'Budget', status: 'approved', new_due_date: date, previous_due_date: date }] },
  '/api/collections/efforts/1': { efforts: [{ id: 1, effort_at: today, mode: 'call', category: 'committed', commitment_date: date, payment_arrangement: 'Deposit', contact_person: 'Ms. R', remarks: 'ok', by_name: 'Paolo' }] },
  '/api/collections/statement/1': { client, invoices: [invoice], receipts: [{ id: 1, receipt_no: 'OR-1', invoice_no: 'INV-1', amount: 100, method: 'cash', received_at: date }], balance: 15556.25 },
  '/api/disbursements': { disbursements: [{ id: 1, voucher_no: 'PV-1', type: 'remittance', payee_name: 'Malayan', amount: 13781.25, mode: 'cheque', requested_by: 99, requested_by_name: 'Grace', reviewed_by_name: null, approved_by_name: null, status: 'pending_review', paid_at: null }, { id: 2, voucher_no: 'PV-2', type: 'refund', payee_name: 'Acme', amount: 100, mode: 'credit_to_account', requested_by: 1, status: 'approved' }] },
  '/api/accounting/remittances/due': { due: [{ insurer_id: 1, insurer_name: 'Malayan', policies: 1, amount: 13781.25, policy_ids: [1] }] },
  '/api/accounting/remittances': { remittances: [{ id: 1, voucher_no: 'RS-1', insurer_name: 'Malayan', amount: 13781.25, policy_ids: [1], status: 'extracted', disbursement_status: null, cheque_no: null, paid_at: null }] },
  '/api/refunds': { refunds: [{ id: 1, rrf_no: 'RRF-1', client_name: 'Acme', amount: 100, payment_mode: 'credit_to_account', reason: 'Dup', requested_by: 99, requested_by_name: 'Maria', reviewed_by_name: null, approved_by_name: null, status: 'submitted', voucher_no: null }, { id: 2, rrf_no: 'RRF-2', client_name: 'Acme', amount: 50, payment_mode: 'cheque', reason: 'x', requested_by: 99, status: 'reviewed', voucher_no: 'PV-2', disbursement_status: 'approved' }] },
  '/api/accounting/accounts': { accounts: [{ code: '1000', name: 'Cash', type: 'asset' }, { code: '3000', name: 'Retained', type: 'equity' }] },
  '/api/accounting/journals': { journals: [{ id: 1, jv_no: 'JV-1', entry_date: date, period: '2026-09', description: 'Booking', lines: [{ id: 1, account_code: '1000', account_name: 'Cash', debit: 100, credit: 0 }, { id: 2, account_code: '3000', account_name: 'Retained', debit: 0, credit: 100 }] }] },
  '/api/accounting/trial-balance': { rows: [{ code: '1000', name: 'Cash', type: 'asset', debit: 100, credit: 0 }], totals: { debit: 100, credit: 100 } },
  '/api/accounting/periods': { periods: [{ period: '2026-09', status: 'open', closed_at: null, reopened_at: null }, { period: '2026-08', status: 'closed', closed_at: today, reopened_at: null }], fiscalYears: [{ year: 2025, status: 'closed', closed_at: today }] },
  '/api/accounting/soa-recons': { recons: [{ id: 1, recon_no: 'SOA-1', insurer_name: 'Malayan', statement_total: 10, ledger_total: 5, variance: 5, status: 'discrepancy', created_at: today }] },
  '/api/claims': { claims: [claim] },
  '/api/claims/1': { claim, events: [{ id: 1, event: 'registered', note: 'x', at: today, user_name: 'Jenny' }], documents: [{ id: 1, name: 'Claim form', required: true, received: true, received_at: today }, { id: 2, name: 'Photos', required: true, received: false }] },
  '/api/renewals/pipeline': { window: 140, policies: [{ id: 1, policy_no: 'POL-1', client_name: 'Acme', product_name: 'Motor', expiry_date: date, days_to_expiry: 30, premium: 12500, sum_insured: 1000000, notices: ['initial'], disposition: 'for_renewal', client_accepted: true, renewal_policy_no: null, has_open_claim: true }, { id: 2, policy_no: 'POL-2', client_name: 'Acme', product_name: 'Motor', expiry_date: date, days_to_expiry: 100, premium: 1, sum_insured: 1, notices: null, disposition: null, client_accepted: false, renewal_policy_no: 'POL-9', renewal_status: 'placed', has_open_claim: false }] },
  '/api/reinsurance/treaties': { treaties: [{ id: 1, code: 'QS-FIRE', name: 'Fire QS', reinsurer: 'Munich Re', reinsurer_rating: 'AA', type: 'quota_share', cession_rate: 0.4, capacity: 1, utilised: 0, cessions: 0, inception_date: date, expiry_date: date }] },
  '/api/reinsurance/cessions': { cessions: [{ id: 1, policy_no: 'POL-1', client_name: 'Acme', treaty_code: 'QS-FIRE', reinsurer: 'Munich Re', ceded_sum_insured: 1, ceded_premium: 1 }] },
  '/api/reinsurance/placements': { placements: [{ id: 1, request_no: 'FAC-1', cedant: 'TSU', risk_description: 'Plant', sum_insured: 1, requested_share: 0.4, placed_share: 0.25, ack_due_at: today, acknowledged_at: null, ack_overdue: true, slip_due_at: null, slip_prepared_at: null, slip_overdue: false, debit_note_no: null, status: 'requested' }, { id: 2, request_no: 'FAC-2', cedant: 'TSU', risk_description: 'Ship', sum_insured: 1, requested_share: 0.4, placed_share: 0.4, ack_due_at: today, acknowledged_at: today, ack_overdue: false, slip_due_at: today, slip_prepared_at: today, slip_overdue: false, debit_note_no: 'DN-1', status: 'slip_prepared' }] },
  '/api/submitted-policies/batches': { batches: [{ id: 1, batch_no: 'SPB-1', insurer_name: 'STD', file_name: 'x.csv', total_rows: 3, masterlist: 1, renewal: 0, fallout: 1, excluded: 1, uploaded_at: today }] },
  '/api/submitted-policies/batches/1': { batch: { id: 1, batch_no: 'SPB-1', file_name: 'x.csv' }, rows: [{ id: 1, policy_no_raw: 'EXT-1', client_name_raw: 'Borrower', insurer_name_raw: 'Other', premium_raw: 100, expiry_date: date, classification: 'fallout', matched_policy_no: null, adequacy_status: 'pending', iaaf_no: null, findings: null }] },
  '/api/submitted-policies/expiring': { window: 150, rows: [{ id: 1, policy_no_raw: 'EXT-1', client_name_raw: 'Borrower', insurer_name_raw: null, expiry_date: date, days_to_expiry: 100, classification: 'fallout', adequacy_status: 'iaaf_issued', batch_no: 'SPB-1' }] },
  '/api/employee-benefits/schemes': { schemes: [{ id: 1, scheme_no: 'EB-1', client_name: 'Acme', plan_name: 'Gold', insurer_name: 'Pru', active_members: 2, covered_lives: 4, annual_premium: 48000, proposals_received: 1, expiry_date: date, status: 'remarketing' }] },
  '/api/employee-benefits/schemes/1': { scheme: { id: 1, scheme_no: 'EB-1', plan_name: 'Gold', covered_lives: 4, annual_premium: 48000, status: 'remarketing', bor_received: true, tor_prepared: false, isacom_required: true }, members: [{ id: 1, member_no: 'E1', name: 'Alice', birth_date: date, dependents: 2, status: 'active' }], proposals: [{ id: 1, insurer_id: 1, insurer_name: 'Pru', accredited: true, premium_per_life: 11000, benefits: 'MBL', capabilities_score: 80, status: 'received' }, { id: 2, insurer_id: 2, insurer_name: 'NAC', accredited: false, premium_per_life: null, status: 'requested' }] },
  '/api/servicing/requests': { requests: [{ id: 1, request_no: 'SR-1', case_type: 'account_related', client_name: 'Acme', channel: 'phone', category: 'billing', owning_unit: 'OPS', identity_verified: true, tat_due_at: today, past_tat: true, description: 'Statement', return_reason: null, status: 'open' }, { id: 2, request_no: 'SR-2', case_type: 'general_inquiry', channel: 'email', category: 'inquiry', owning_unit: 'CSF', identity_verified: false, tat_due_at: today, past_tat: false, description: 'Hours', status: 'closed' }] },
  '/api/servicing/search': { clients: [client], policies: [policy], invoices: [invoice] },
  '/api/users': { users: [{ id: 1, username: 'admin', full_name: 'System Administrator', role_code: 'ADMIN', role_name: 'System Administrator', department: 'IT', status: 'active', last_login_at: today }, { id: 2, username: 'cashier', full_name: 'Liza', role_code: 'CASHIER', role_name: 'Cashier', department: 'Ops', status: 'active', last_login_at: null }] },
  '/api/users/roles': { roles: [{ code: 'ADMIN', name: 'System Administrator', modules: ['NB', 'OPS'], can_approve: true }, { code: 'CASHIER', name: 'Cashier', modules: ['OPS'], can_approve: false }] },
  '/api/data-migration/batches': { batches: [{ id: 1, batch_no: 'MIG-1', entity: 'policies', source_count: 10, loaded_count: 9, source_value: 100, loaded_value: 100, status: 'disposition_required', disposition_note: null, created_at: today }] },
};

const POST_FIXTURES: Record<string, unknown> = { '/rate': FIXTURES['/api/products/1/rate'] };

export function fixtureFor(url: string, method = 'GET'): unknown {
  const path = url.split('?')[0];
  const table = method === 'GET' ? FIXTURES : POST_FIXTURES;
  const key = Object.keys(table).find((k) => path.endsWith(k));
  return key ? table[key] : { ok: true, id: 1, status: 'ok', approvalId: 1, policyId: 1, requestNo: 'SR-9', owningUnit: 'OPS', quoteNo: 'QT-9', policyNo: 'POL-2026-00009', claimNo: 'CLM-9', receiptNo: 'OR-9', paymentNo: 'PAY-9', reconNo: 'PRC-9', batchNo: 'SPB-9', added: 1, updated: 0, screening: { status: 'clear', tier: 'low' }, clientNo: 'CLT-9', netResult: 0, premiumVariance: 0, cededSumInsured: 1, cededPremium: 1, matched: 1, discrepancy: 0, unbooked: 0, masterlist: 1, renewal: 0, fallout: 0, excluded: 0, jvNo: 'JV-9', period: '2026-09', amount: 1, beyondCreditTerm: false, iaafNo: 'IAAF-9', debitNoteNo: 'DN-9', unapplied: 0, applied: 1, remaining: 0 };
}
